### ISSUE TITLE
Compilation failure: byte[] cannot be converted to ByteString

### ISSUE THREAD

**Issue by LibertyWalk** [wadesalazar/NIFI-OPCUA#14]
I tried to "mvn clean install" this project to get the necessary files for integration in NIFI.
However, I'm getting the following error message:
C:\Users\libertywalk\Downloads\nifi-opcua-bundle_hasmap\nifi-opcua-bundle\nifi-opcua-service\src\main\java\com\hashmapinc\tempus\processors\StandardOPCUAService.java:[320,73] error: incompatible types: byte[] cannot be converted to ByteString

I'm not quite sure why this occurs. Here's my environment;

mvn -version output:
Maven home: C:\Users\libertywalk\apache-maven-3.5.2-bin\apache-maven-3.5.2\bin..
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.8.0_162\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "x86", family: "windows"
OPC Foundation Stack Version:
1.03.342.1-SNAPSHOT
nifi-opcua-bundle branch: master

**Comment by mballabani** [comment]
Same problem for me
